### ISSUE TITLE
c.n.i.p.insights.InsightsRunner

### ISSUE THREAD

**Issue by alexandrudu** [newrelic/newrelic-unix-monitor#15]
Hi guys,

Running the latest release of newrelix unix monitor for some time now and it works great....for some reason on the 24th of april between 12:02am and 4:43am EST all unix hosts (more than 50) stopped reporting and when i look inside the logs i see this error
2019-04-24 04:43:56 [pool-2-thread-1] ERROR c.n.i.p.insights.InsightsRunner - Error posting events to Insights for agent-[**hostname]
but after that 4h period the hosts started reporting again and the error went away... just curious what the error is since there was no network drop or anything and nothing has changed in the environment (infra)...
any ideas ?

**Comment by sschwartzman** [comment]
Hi @alexandrudu, as this 'agent' simply uses the Insights REST API to post events, this error would indicate that it had some connectivity issues back to the mothership. I looked into it and there weren't any outages during this time, so I am unsure as to what could have caused it. Is it possible that there was a networking issue on your end?

I don't know that's there's much we can do posthumously about it, other than that the next time you see this error, to report it immediately to Support. That this particular agent is unsupported, you would need to indicate to them not that it's an error with the agent, but that you are having general connectivity issues to the Insights REST endpoint. So when it does happen, you could do a simple REST POST from any of these boxes to the Insights endpoint to test connectivity, and if it fails, then you have something you can go to Support with.

Here's a sample payload (save as `example_events.json`):
[
  {
    "eventType":"TestEvent",
    "account":3,
    "amount":259.54
  },
  {
    "eventType":"TestEvent",
    "account":5,
    "amount":12309,
    "product":"Item"
  }
]

Here's a sample curl command to run for testing (replace the insert key and your account ID accordingly):
`
gzip -c example_events.json | curl -X POST -H "Content-Type: application/json" -H "X-Insert-Key: YOUR_KEY_HERE" -H "Content-Encoding: gzip" https://insights-collector.newrelic.com/v1/accounts/YOUR_ACCOUNT_ID/events --data-binary @-
`

Does that work for you?

**Comment by alexandrudu** [comment]
K thank you for the quick answer.  I know how to post an event to insights as i am already doing so with some other custom events.... but i will try to investigate more on my end... Those servers have lots of apps running on the and none went down during that time... i also asked newrelic if they had any issues with insights during that time and they said no.... as mentioned its the first time it happens ... if i find the root cause of it i will post it here for others... thx again.

**Comment by sschwartzman** [comment]
Thanks for understanding. I will close this out for now, if you find something in your poking around that indicates an issue with the agent itself, please let me know and we will dive into it.
