### ISSUE TITLE
Doesn't run with Java 10

### ISSUE THREAD

**Issue by mariomac** [newrelic/newrelic-unix-monitor#2]
It seems the system recognizes it as an old Java version:

```
unix-infra-monitor $ ./pluginctl.sh
Plugin location: /Users/mmacias/code/unix-infra-monitor/target/unix-infra-monitor
Java location: /usr/bin/java
Java version: 10.0.2
ERROR: New Relic Unix Plugin will not work with Java versions older than 1.6.
Please edit pluginctl.sh and set PLUGIN_JAVA to a Java distro (Sun/Oracle, IBM, OpenJDK) v1.6 or above.
```

**Comment by sschwartzman** [comment]
Good catch! I just need to update the logic in the script.

**Comment by sschwartzman** [comment]
@mariomac can you change this at the end of line 78 of pluginctl.sh:
```END{print array[2]}'```
to this?
```END{print array[1]}'```
And let me know the result?

**Comment by sschwartzman** [comment]
@mariomac - I've fixed pluginctl.sh to work with Java 10 properly. Can you try it out so that we can close this out?

New version here: https://raw.githubusercontent.com/newrelic/newrelic-unix-monitor/master/pluginctl.sh

**Comment by sschwartzman** [comment]
@mariomac closing this out for now. Let me know if you try the script and it still doesn't work with Java 10.
