### ISSUE TITLE
Host not showing in PLUGIN New Relic

### ISSUE THREAD

**Issue by crosshaire** [newrelic/newrelic-unix-monitor#21]
Hi sschwartzman,

New Plugin installed and Running. However it doesn't show in NR (plugins>Unix) tab

Please assist 

Acount Id - Filled out correctly
Insights Keys - Generated
API Keys Generated

[root@ID:/home/eouxadm2/newrelic-unix-monitor/config] $ cat plugin.json
{
        "global": {
                "OS": "auto",
                "debug": false,
                "account_id": "XXXXX",
                "insights_mode": {
                        "insights_insert_key": "XXXXXXX",
                        "insights_data_center": "US"
                },
                "dashboards": {
                        "admin_api_key": "XXXXXX",
                        "integration_guid": "UNIX.Infra.Monitor",
                        "dashboard_install": "command_line"
                }
        },
        "agents": [
                {
                        "name": "auto"
                }
        ]
}

[root@ID:/home/eouxadm2/newrelic-unix-monitor] $ ./pluginctl.sh start
Plugin location: /home/eouxadm2/newrelic-unix-monitor
Java location: /usr/java8_64/jre/bin/java
Java version: 1.8.0_201
Java major version: 8
Running as plugin that posts directly to Insights.

Checking New Relic Unix Monitor
New Relic Unix Monitor is not running
Deleting logs
Starting New Relic Unix Monitor
New Relic Unix Monitor started with PID 56688842

Dashboards: Installing dashboards for New Relic Unix Monitor.
Dashboards: Using wget to initiate dashboard install.
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
./pluginctl.sh[41]: --quiet:  not found.
Dashboards: Installation failed.
Dashboards: No response recorded, check settings in config/plugin.json.

[root@ID:/home/eouxadm2/newrelic-unix-monitor] $ ./pluginctl.sh status
Plugin location: /home/eouxadm2/newrelic-unix-monitor
Java location: /usr/java8_64/jre/bin/java
Java version: 1.8.0_201
Java major version: 8
Running as plugin that posts directly to Insights.

Checking New Relic Unix Monitor
New Relic Unix Monitor is running with PID 56688842
[root@ID:/home/eouxadm2/newrelic-unix-monitor] $

**Comment by sschwartzman** [comment]
@crosshaire this is not a Plugin, it writes straight to Insights, so the data is found there.

See step 7: https://github.com/newrelic/newrelic-unix-monitor/#installation--usage-overview
