### ISSUE TITLE
proxy password encryption

### ISSUE THREAD

**Issue by haihongren** [newrelic/newrelic-unix-monitor#22]
Currently the proxy password is in clear text in the config file, is there anyway to encrypt the proxy password? 

		"proxy": {
			"proxy_host": "enter_proxy_host",
			"proxy_port": 5443,
			"proxy_username": "enter_proxy_username",
			"proxy_password": "enter_proxy_password"
		}

**Comment by sschwartzman** [comment]
Handled in issue  #26 , closing!
