### ISSUE TITLE
Issue with dashboard configuration on starting unix agent on AIX 

### ISSUE THREAD

**Issue by StefanMors83** [newrelic/newrelic-unix-monitor#23]
When starting my Unix agent I get the following messages: 

Dashboards: Installing dashboards for New Relic Unix Monitor.
Dashboards: Using wget to initiate dashboard install.
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
./pluginctl.sh[44]: --quiet: not found.
Dashboards: Installation failed.
Dashboards: No response recorded, check settings in config/plugin.json.

I added my API key to the configuration file: 

                "dashboards": {
                        "admin_api_key": "NRAA-e*****",
                        "integration_guid": "UNIX.Infra.Monitor",
                        "dashboard_install": "command_line",
                        "force_deploy": true
                }

but did not make any further configuration changes. Please if their is some documentation about this part please let me know.

Thanks for your help

**Comment by sdewitt-newrelic** [comment]
Hi @StefanMors83 can you provide the output of the following?

`uname -a && wget --version`

**Comment by StefanMors83** [comment]
Hi Scott, here is the output: 

root@AFPINTERLAT3:/# uname -a && wget --version
AIX AFPINTERLAT3 2 7 00CE14F54C00
GNU Wget 1.20.3 built on aix5.1.0.0.

-cares +digest -gpgme +https -ipv6 -iri +large-file -metalink +nls 
+ntlm +opie -psl +ssl/openssl 

Wgetrc: 
    /opt/freeware/etc/wgetrc (system)
Locale: 
    /opt/freeware/share/locale 
Compile: 
    xlc_r -D_LARGE_FILES -DHAVE_CONFIG_H 
    -DSYSTEM_WGETRC="/opt/freeware/etc/wgetrc" 
    -DLOCALEDIR="/opt/freeware/share/locale" -I. -I../lib -I../lib 
    -D_THREAD_SAFE -I/opt/freeware/include -I/opt/freeware/include 
    -I/opt/freeware/include -DHAVE_LIBSSL -I/opt/freeware/include 
    -DNDEBUG -qmaxmem=262144 -DSYSV -D_AIX -D_AIX32 -D_AIX41 -D_AIX43 
    -D_AIX51 -D_ALL_SOURCE -DFUNCPROTO=15 -O3 -qstrict 
    -I/opt/freeware/include 
Link: 
    xlc_r -D_LARGE_FILES -I/opt/freeware/include 
    -I/opt/freeware/include -DHAVE_LIBSSL -I/opt/freeware/include 
    -DNDEBUG -qmaxmem=262144 -DSYSV -D_AIX -D_AIX32 -D_AIX41 -D_AIX43 
    -D_AIX51 -D_ALL_SOURCE -DFUNCPROTO=15 -O3 -qstrict 
    -I/opt/freeware/include -L/opt/freeware/lib 
    -Wl,-bmaxdata:0x80000000 -L/opt/freeware/lib -lpcre 
    -L/opt/freeware/lib -lssl -lcrypto -L/opt/freeware/lib -lz 
    ftp-opie.o openssl.o http-ntlm.o ../lib/libgnu.a 
    /opt/freeware/lib/libiconv.a /opt/freeware/lib/libintl.a 
    /opt/freeware/lib/libiconv.a /opt/freeware/lib/libunistring.a 
    /opt/freeware/lib/libiconv.a 

Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later
<http://www.gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Originally written by Hrvoje Niksic <hniksic@xemacs.org>.
Please send bug reports and questions to <bug-wget@gnu.org>.
root@AFPINTERLAT3:/# 


Regards   



Stefan Mörs
 Av. Providencia 655

SSO - Server Support Specialist
 Santiago De Chile, 750-0261
Global Technology Services / SSO Chile
 Chile
Phone:
+56996392470
 

e-mail:
stefanmo@cl.ibm.com

**Comment by sdewitt-newrelic** [comment]
@StefanMors83 One more if you don't mind.

`wget --help`

I am thinking that the version of `wget` you are using does not support the `--quiet` option.  That option is specified in the `pluginctl.sh` file here:

https://github.com/newrelic/newrelic-unix-monitor/blob/master/pluginctl.sh#L268

**Comment by StefanMors83** [comment]
Scott, 

        its seems that the option is there: 

root@AFPINTERLAT3:/# wget --help | grep quiet
  -q,  --quiet                     quiet (no output)
  -nv, --no-verbose                turn off verboseness, without being 
quiet
root@AFPINTERLAT3:/# 

Full output: 



Regards   



Stefan Mörs
 Av. Providencia 655

SSO - Server Support Specialist
 Santiago De Chile, 750-0261
Global Technology Services / SSO Chile
 Chile
Phone:
+56996392470
 

e-mail:
stefanmo@cl.ibm.com

**Comment by sdewitt-newrelic** [comment]
@StefanMors83 this PR should fix your issue.
