### ISSUE TITLE
Unclear documentation about credentials obfuscation 

### ISSUE THREAD

**Issue by aries-zhang** [newrelic/newrelic-unix-monitor#26]
Thanks for providing such a great feature, but the documentation in README.md is not quite clear about:

1. What should be used as `OBSCURING_KEY`? 

Guessing it can be a random string? If so, would be nice to explicitly mention it in the docs.

2. Shall I provide the value of `OBSCURING_KEY` in the config file plugin.json?

Tested in my env and it did not work if just put `proxy_password_obfuscated` in plugin.json like what's suggested in step 3 -- got below error in the logs: 

```
2020-10-16 11:30:41 [pool-2-thread-1] ERROR c.n.insights.publish.InsightsClient - Connection reset
2020-10-16 11:30:41 [pool-2-thread-1] ERROR c.n.i.p.insights.InsightsRunner - Error posting events to Insights for agent***
```

Guessing again the OBSCURING_KEY is needed to decrypt it, so tried to set env var in step 2 (although I would interpret it as an alternative way to provide a parameter to newrerlic-cli) and it did not work neither.

Would be expecting a clear instruction about how to properly use this feature. Thanks in advance!

**Comment by haihongren** [comment]
@sschwartzman 
I think the unix plugin needs to be compiled with the infra-publish version 2.3.1, which supports `proxy_username_obfuscated`.  

The current Unix plugin seems to be compiled with infra-publish version 2.3.0.

**Comment by sschwartzman** [comment]
Good catch @haihongren! I've updated the maven POM and updated the release. @aries-zhang can you check it out?

https://github.com/newrelic/newrelic-unix-monitor/releases/tag/0.2.1

For `OBSCURING_KEY`, it can be any string you want it to be, you just have to use it in both the CLI and the Unix Monitor. For the latter, you'll have to uncomment `NEW_RELIC_CONFIG_OBSCURING_KEY` in `pluginctl.sh` and set it to the same value (or envvar).

I've updated the README to make this all clearer. Please take a look at that too.
https://github.com/newrelic/newrelic-unix-monitor/blob/master/README.md#credential-obfuscation

**Comment by sschwartzman** [comment]
Any update @haihongren @aries-zhang? Should I close this out?
