### ISSUE TITLE
Log Forwarding

### ISSUE THREAD

**Issue by satya2p** [newrelic/newrelic-unix-monitor#27]
Do we have an option to forward AIX logs from a XYZ directory to NewRelic like we have an option in infrastructure agent.

**Comment by sschwartzman** [comment]
Sorry @satya2p, it does not. Since AIX has syslog support, you could use it to forward to our TCP endpoint: https://docs.newrelic.com/docs/logs/log-management/log-api/use-tcp-endpoint-forward-logs-new-relic/
