### ISSUE TITLE
Installation stuck post running the command pluginctl.sh

### ISSUE THREAD

**Issue by robingarg8351** [newrelic/newrelic-unix-monitor#28]
Dear Team-

I got stuck at installation step after running the pluginctl.sh at last steps. Please refer to snapshot for reference
![2_HARD_CODED_PATH_TO_JAVA](https://user-images.githubusercontent.com/77995323/105767508-1b65ac00-5f81-11eb-8173-2f9a94a3c90e.PNG)
![3_HARD_CODED_PATH_TO_JAVA](https://user-images.githubusercontent.com/77995323/105767509-1bfe4280-5f81-11eb-9b15-632231a52145.PNG)
![HARD_CODED_PATH_TO_JAVA](https://user-images.githubusercontent.com/77995323/105767510-1bfe4280-5f81-11eb-9212-4a1d1461ebbc.PNG)

**Comment by robingarg8351** [comment]
Tried Stop the PID and again restarted. Still same issue

dfwrstdb-07:/opt/newrelic-unix-monitor# ./pluginctl.sh
Plugin location: /opt/newrelic-unix-monitor/
Java location: /usr/java7_64/bin/java
Java version: 1.7.0
Java major version: 7
Running as plugin that posts directly to Insights.
Usage: ./pluginctl.sh [status|start|stop|stopremlogs|restart|dashboards|dashboards_redeploy] [debug]
dfwrstdb-07:/opt/newrelic-unix-monitor# ./pluginctl.sh status
Plugin location: /opt/newrelic-unix-monitor/
Java location: /usr/java7_64/bin/java
Java version: 1.7.0
Java major version: 7
Running as plugin that posts directly to Insights.

Checking New Relic Unix Monitor
Process dead but /opt/newrelic-unix-monitor//logs/plugin.pid exists
Deleting /opt/newrelic-unix-monitor//logs/plugin.pid
dfwrstdb-07:/opt/newrelic-unix-monitor#

**Comment by abhipandey695** [comment]
This issue was closed after trying "Disabling at plugin startup" with the AIX hosts getting access to send data to New Relic.

**Comment by sschwartzman** [comment]
Thanks @abhipandey695
