### ISSUE TITLE
Get the Hung Process running on Solaris VMs

### ISSUE THREAD

**Issue by SunnyWgl** [newrelic/newrelic-unix-monitor#29]
We do have requirement to kill the hung process running more than 3 hours and the process is running on Solaris VM. 

There is a process dashboard but the output is not having proper information like time etc. The requirement is to have the output of "prstat -a" in the dashboard.

1. Process details by executing command - prstat -a | grep '<<process name>>'  
2. the updated plugin-commands-solaris_xx.json file which consists of " prstat -a "output to be displayed in the dashboard

Attached is the screenshot for your reference.
![hungprocess](https://user-images.githubusercontent.com/79485676/108782063-ff284f80-75be-11eb-9b08-631ed77ef638.jpg)

**Comment by SunnyWgl** [comment]
This is a new feature request

**Comment by haihongren** [comment]
@SunnyWgl  

What's the Solaris OS version, and update version? 
Please run `#ps -eo` and send me the output.

**Comment by SunnyWgl** [comment]
@haihongren 

The solaris version is - $ uname -a
SunOS  5.10 Generic_150400-68 sun4v sparc sun4v

When i execute the command "ps -eo" it is throwing up with following options

$ps -eo
ps: option requires an argument -- o
usage: ps [ -aAdeflcjLPyZ ] [ -o format ] [ -t termlist ]
        [ -u userlist ] [ -U userlist ] [ -G grouplist ]
        [ -p proclist ] [ -g pgrplist ] [ -s sidlist ] [ -z zonelist ]
  'format' is one or more of:
        user ruser group rgroup uid ruid gid rgid pid ppid pgid sid taskid ctid
        pri opri pcpu pmem vsz rss osz nice class time etime stime zone zoneid
        f s c lwp nlwp psr tty addr wchan fname comm args projid project pse

**Comment by haihongren** [comment]
@SunnyWgl 

It looks the following command provides the info avail in `prstat`, including "user,time and nlwp".

`#ps -eo pid,s,pcpu,pmem,rss,vsz,args,user,time,nlwp`

Instead of creating a separate data collection for `prstat`. We can extend the current `ps` data collection. 
Will that be sufficient for your use case?

**Comment by SunnyWgl** [comment]
@haihongren yeah that's fine and also include the process name and the attributes mentioned in the screenshot above

**Comment by haihongren** [comment]
@SunnyWgl 
Can you please send me the output from the servers (one from Solaris10, one from Solaris11)?

`#ps -eo pid,s,pcpu,pmem,rss,vsz,args,user,time,nlwp`

**Comment by SunnyWgl** [comment]
@haihongren  - Attached is the zip files having the output of the command from Solaris10 and Solaris11. 

[Solaris_11_output.zip](https://github.com/newrelic/newrelic-unix-monitor/files/6146142/Solaris_11_output.zip)
