### ISSUE TITLE
Dashboard format changed

### ISSUE THREAD

**Issue by TrawfazzzMosowski** [newrelic/newrelic-unix-monitor#31]
The dashboards will not upload because the dashboard format has changed.

**Comment by sschwartzman** [comment]
Good call-out Tralfaz. @thezackm and I resolved this by moving the Dashboards into the Quickstarts NR1 app, and removing all the dashboard install junk from the unix monitor itself. https://github.com/newrelic/newrelic-unix-monitor/releases/tag/0.2.3

--Mr. Spacely
