### ISSUE TITLE
Regex is missing for Zombie processes

### ISSUE THREAD

**Issue by sandeep-43** [newrelic/newrelic-unix-monitor#33]
In the Process monitoring segment under "plugin-commands-aix.json", the regex doesn't satisfy the line for zombie processes. Please update the regex to include that. Plus, a better command to use would be ps aux or ps ueg, which would include user info as well.

**Comment by sschwartzman** [comment]
Can you post what the command looks like with Zombie processes such that the regex can be updated? I lost access to my AIX test bed recently so I can't test it out.

If you want to make any changes to the config, i.e. for PS AUX, you are welcome to PR them to this repo.
