### ISSUE TITLE
Cannot compile: missing dependency

### ISSUE THREAD

**Issue by osaman88** [newrelic/newrelic-unix-monitor#34]
I am trying to compile from scratch. It fails thus:

[ERROR] Failed to execute goal on project newrelic-unix-monitor: Could not resolve dependencies for project com.newrelic.experts:newrelic-unix-monitor:jar:0.2.4: Could not find artifact com.newrelic.experts:infra_publish:jar:2.3.2 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

The pom.xml has the following dependency:
		<dependency>
			<groupId>com.newrelic.experts</groupId>
			<artifactId>infra_publish</artifactId>
			<version>2.3.2</version>
		</dependency>

However, Maven fails to find such a version. The latest available on
https://repo.maven.apache.org/maven2/com/newrelic/experts/infra_publish/ 
appears to be 2.3.1

Thanks

Osama

**Comment by sschwartzman** [comment]
Hi @osaman88 - good catch, I made a tweak to "infra_publish" (a package that we maintain internally) and the change hasn't been pushed into maven yet. Until it gets pushed into maven, you can change 2.3.2 to 2.3.1 in your pom and it should compile fine, as the change was minor and likely wouldn't impact you (to be able to handle proxy_port when it's written as a string in the config yaml file).

**Comment by osaman88** [comment]
Thanks @sschwartzman  for quick response! I am not using proxies currently. I was able to compile with 2.3.1 successfully.
