### ISSUE TITLE
Computational memory percentage for AIX server

### ISSUE THREAD

**Issue by Pritamdey148** [newrelic/newrelic-unix-monitor#35]
Need to get the Computational memory percentage for AIX server , not sure if new relic is collecting this information from the servers or else we have make some changes the agent script for the same.

**Comment by sschwartzman** [comment]
The percentage can be easily computed with an NRQL query against the "Memory.Total", "Memory.Used" or "Memory.Available" metrics being grabbed from svmon:

https://github.com/newrelic/newrelic-unix-monitor/blob/master/config/plugin-commands-aix.json#L378

Beyond that, the percentage would be derived (per host) like so:

```
SELECT 100*latest(memory.used)/latest(memory.total)) as 'Computational Memory Percentage' FROM unixMonitor:Stats SINCE 1 HOUR AGO FACET hostname
````
