### ISSUE TITLE
Capture Uptime for the AIX Server

### ISSUE THREAD

**Issue by sri-shetty** [newrelic/newrelic-unix-monitor#36]
We would like to capture AIX server uptime. The changes that we made to plugin-commands-aix.json is not working, agent stops sending data.
There is a uptime command in the plugin....json file but it is not capturing uptime. Could you please change this expression to capture uptime?
{
			"eventType": "Stats",
			"command": "uptime",
			"mappings": [{
				"expression": ".*load average:\\s+([0-9\\.]+),\\s+([0-9\\.]+),\\s+([0-9\\.]+)",
				"metrics": [{
						"name": "LoadAverage.1 Minute",
						"type": "NORMAL"
					},
					{
						"name": "LoadAverage.5 Minute",
						"type": "NORMAL"
					},
					{
						"name": "LoadAverage.15 Minute",
						"type": "NORMAL"
					}
				]
			}]
		}

We tried to add another command like below but this is not working. Please add option to capture uptime.
		{
            "eventType": "Stats",
            "command": "uptime | awk '{print $3}'",
            "mappings": [{
                "expression": "\\d+",
                "metrics": [{
                    	"name": "Server Uptime",
                   		"type": "NORMAL"
                	}
            	]
            }]
        }

**Comment by sschwartzman** [comment]
@sri-shetty any word from your customer if the version of the AIX config I provided you is working for them? If so, I can put it into the repo and close this out.

**Comment by sri-shetty** [comment]
@sschwartzman - This issue can be closed.
