### ISSUE TITLE
Where are dashboards?

### ISSUE THREAD

**Issue by DavidCarrington** [newrelic/newrelic-unix-monitor#39]
The README points to https://newrelic.github.io/quickstarts-dashboard-library/#/installation (404) which is seemingly replaced by this system: https://newrelic.com/instant-observability/unix/9fdfa9b9-4a83-47e6-a8d5-b23cc05b653a.

I can't find any link that shows or creates sample dashboards.

**Comment by josephmcasey** [comment]
I ran into a similar issue. It looks like [the cmd to install dashboards are only placed in the IBM custom](https://github.com/newrelic/newrelic-unix-monitor/blob/5a2d78e05d2478f44481b0a360a2b4a754ca54c2/customconfig/ibm/pluginctl.sh#L220-L284) `pluginctl.sh`. I didn't really understand why there was such a delineation 

That said, you can find the JAR contains the resources for the dashboards here.
https://github.com/newrelic/newrelic-unix-monitor/tree/5a2d78e05d2478f44481b0a360a2b4a754ca54c2/src/main/resources/dashboards
