### ISSUE TITLE
pluginctl.sh syntax error with /bin/sh

### ISSUE THREAD

**Issue by ernestom** [newrelic/newrelic-unix-monitor#4]
Running the command `./pluginctl.sh start` (as documented in the readme) on my default shell yields the following error:

```
-bash-3.2$ Plugin location: /vagrant/nr/newrelic-unix-monitor-master
Java location: /vagrant/nr/jre1.8.0_181/bin/java
Java version: 1.8.0_181
Java major version: 8
Running as plugin that posts directly to Insights.
./pluginctl.sh: syntax error at line 240: `admin_api_key=$' unexpected
```

Running it with bash fixes it `bash ./pluginctl.sh start`.
Happy to send a PR to either change the shebang, add a note to invoke it with bash, or add a note about this in the readme.

**Comment by sschwartzman** [comment]
Not all OSes that this supports have bash, so I think a note in the readme will be the way to go. You are welcome to PR that. We could also add a commented-out shebang to the script with a comment to switch to it if you get a syntax error.
