### ISSUE TITLE
high load average and polling interval on Solaris10

### ISSUE THREAD

**Issue by Santu439** [newrelic/newrelic-unix-monitor#42]
I see the polling interval seems to be 1 minute and also observed orphan plug-in's sessions getting created causing high load average. Is there a way to change the polling interval and also can the plugin check if there is any instance already running or not. If running or orphan exists can it wait or clear it before new Java process starts? FYI... iostat was causing concern in our case and had to remove it time being.

**Comment by Steve24by7** [comment]
The commands you are executing are system commands and should not be taking too high a load, as the admin we can adjust the commands accordingly, after all its just config.  Congrats for removing the offending commands.
