### ISSUE TITLE
Solaris extension request

### ISSUE THREAD

**Issue by vc102961** [newrelic/newrelic-unix-monitor#43]
Hi 
a customer, for a Solaris system, would like to add the collection of metrics reported by following commands:
echo ::memstat | mdb -k (the same information could be possibly be collected also with kstat,  this is important to get the real memory usage)
<img width="1440" alt="Bildschirmfoto 2022-11-04 um 14 04 36" src="https://user-images.githubusercontent.com/74193443/200816504-3c297f27-b4b2-4f87-9ace-859501ba82b4.png">

svcs -xv
fmadm list -s

for the time being I just would need the confirmation that is doable and it could be done in a timely manner if the prospect request it.  Cold provide me this confirmation ?

Thanks

**Comment by Steve24by7** [comment]
Hello.  This app is extensible with a command and a regexp to parse the output.  Simply alter the plugin-commands file to add another section.  Please close this issue if this answer is sufficient.  If not, you will need to post the output of the commands so we can work with you on the regexp for parsing.

**Comment by ricegi** [comment]
To support piping processes we will have to implement the String[] command set for ProcessBuilder constructor List<String> or Runtime.exec(String[] ... )

We'll probably need this for more sophisticated process scenarios. We can just treat everything in the command configuration as an array with suitable delimiting and update the underlying process invoker. 

Will mark this for inclusion in v ~0.3
