### ISSUE TITLE
TLS 1.2 Change more prominent

### ISSUE THREAD

**Issue by jmortley** [newrelic/newrelic-unix-monitor#51]
New Relic recently switched to the TLS 1.2 for all inbound connections at the beginning of February. There is a small mention of how to force tls 1.2 in pluginctl.sh but it should probably be highlighted in the READme now.

**Comment by jmortley** [comment]
In fact the default config should have this on by default
PLUGIN_JAVA_OPTS="$PLUGIN_JAVA_OPTS -Dcom.ibm.jsse2.overrideDefaultTLS=true -Dhttps.protocols=TLSv1.2 -Djdk.tls.client.protocols=TLSv1.2"

**Comment by gsidhwani-nr** [comment]
Thanks Alexander for the feedback !

We will implement this in pluginctl.sh as a default configuration in our next release r1.0.2 by this month end.

Thanks
Gulab

**Comment by gsidhwani-nr** [comment]
Hello Alexander ,
As latest release r1.0.1 is required to be run with JDK8 onwards and hence TLS 1.2 is by default. And hence there is no extra setting is required for TLS.

[JDK 8 (March 2014) will use TLS 1.2 as the default.](https://blogs.oracle.com/java/post/jdk-8-will-use-tls-12-as-default)

And hence the latest release r1.0.1 fit to use.
