### ISSUE TITLE
credential encryption issue on solaris 10

### ISSUE THREAD

**Issue by kururaj** [newrelic/newrelic-unix-monitor#69]
While following the documentation to obfuscate the ingest key, I appended the insights_insert_key_obfuscated attribute to the plugin.json file as instructed.

However, the log file is showing an error indicating that insights_insert_key is empty or null.

Here is the documentation link: [New Relic Unix Monitoring Integration](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/unix-monitoring-integration/).

The template used for plugin.json :

{
  "global": {
    "OS": "auto",
    "account_id": "123",
    "fedramp": "false",
    "insights_mode": {
    "insights_insert_key_obfuscated":"ABCDEF",
          "insights_data_center": ""
    },
    "proxy": {
      "proxy_host": "hgshadgh",
      "proxy_port": 1234
    }
  },
  "agents": [
    {
      "name": "auto",
      "host": "hostname",
      "static": {
        "attribute1": "attribute1_value",
        "attribute2": 12345
      }
    }
  ]
}

**Comment by gsidhwani-nr** [comment]
This has been resolved in v1.0.3.
